org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Farklı disk köklerindeki (C:\ pub cache / E:\ proje) artımlı derleme önbellek hatasını önler
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
